/**
 * Seed a real game backend for tests: a real `Y.Doc` + a real `Player`.
 *
 * Never mock Yjs or `Player` — CRDT semantics are too subtle to fake and a real
 * doc is cheap. `renderWithGame` (harness.tsx) wraps this to also populate the
 * Zustand stores; use `seedGame` directly in logic tests that don't render.
 */

import * as Y from 'yjs';
import { Player } from '@/features/player/Player';
import { Deck } from '@/features/player/Deck';
import type { Card } from '@/features/player/types';

export interface SeedGameOptions {
  /** Local player id. Defaults to a stable test id. */
  playerId?: string;
  /** Cards to place into the player's hand. */
  hand?: Card[];
  /** Cards to load into the deck. Ids are regenerated by `Deck` to avoid collisions. */
  deck?: Card[];
  /** Starting life total. Defaults to 40. */
  initialHealth?: number;
}

export interface SeededGame {
  yDoc: Y.Doc;
  player: Player;
  playerId: string;
}

export function seedGame(opts: SeedGameOptions = {}): SeededGame {
  const playerId = opts.playerId ?? 'test-player';
  const yDoc = new Y.Doc();

  // A Deck built from explicit cards, or an empty one when the test only seeds a hand.
  const deck = opts.deck && opts.deck.length > 0 ? new Deck(opts.deck) : new Deck(undefined, 0);
  const player = new Player(playerId, yDoc, deck, { initialHealth: opts.initialHealth ?? 40 });

  opts.hand?.forEach((card) => player.placeCardInPile(card, 'hand'));

  return { yDoc, player, playerId };
}
