import { PreconList, PreconSummary } from './types';

/**
 * Reads the precon catalog served as static assets from `public/precons/`
 * (generated by `scripts/build-precons.mjs`). The manifest is small enough to
 * fetch up front; each deck's card list is fetched only when a precon is chosen.
 */
export class PreconCatalogService {
  constructor(private readonly basePath: string = '/precons') {}

  /** The full catalog for the picker — summaries only, no card lists. */
  async getCatalog(): Promise<PreconSummary[]> {
    const res = await fetch(`${this.basePath}/index.json`);
    if (!res.ok) {
      throw new Error(`Failed to load precon catalog (${res.status})`);
    }
    return (await res.json()) as PreconSummary[];
  }

  /** One precon's card list (the lightweight entries to hydrate). */
  async getList(id: string): Promise<PreconList> {
    const res = await fetch(`${this.basePath}/${encodeURIComponent(id)}.json`);
    if (!res.ok) {
      throw new Error(`Failed to load precon "${id}" (${res.status})`);
    }
    return (await res.json()) as PreconList;
  }
}
