/**
 * Shapes of the precon catalog served from `public/precons/` (generated by
 * `scripts/build-precons.mjs`). These are deliberately lightweight — a precon
 * ships as a list of printing coordinates, not hydrated cards. Card images and
 * oracle text are resolved on demand via the card API when a precon is chosen.
 */

/** One card row in a precon list — enough to resolve a printing exactly. */
export interface PreconEntry {
  quantity: number;
  name: string;
  setCode: string;
  collectorNumber: string;
  scryfallId: string;
  /** True for the deck's commander row(s); auto-drawn into the opening hand. */
  commander: boolean;
}

/** A single precon's full card list (`public/precons/<id>.json`). */
export interface PreconList {
  id: string;
  name: string;
  /** Human-readable product/set name, e.g. "Tarkir Dragonstorm Commander". */
  set: string;
  cards: PreconEntry[];
}

/** Catalog row for the picker (`public/precons/index.json`) — no card list. */
export interface PreconSummary {
  id: string;
  name: string;
  set: string;
  /** Machine set code of the deck's set, e.g. "tdc". */
  setCode: string;
  /** Color identity in WUBRG order, e.g. ["W", "B", "G"]. */
  colors: string[];
  commanderNames: string[];
  cardCount: number;
}
